defaultDataset: ga4_core
defaultLocation: US
defaultProject: your-gcp-project
vars:
    CORE_DATASET: ga4_core
    REPORTING_DATASET: ga4_reporting
    SOURCE_DATASET: analytics_XXXXXXXXX
    SOURCE_PROJECT: your-gcp-project
    SOURCE_TABLE_PREFIX: events_
    ENVIRONMENT: prod
    HAS_ECOMMERCE: 'false'
